### ISSUE TITLE
Play 2.4 Dependency Injection

### ISSUE THREAD

**Issue by fosskers** [Rhinofly/play-https-redirect-filter#3]
`Global.scala` is being phased out. How do you recommend we use this plugin if we have no `Global.scala`?

**Comment by EECOLOR** [comment]
We have not yet finished the `2.4.x` branch. On top of that it depends on the strategy you use. We use manual injection:

```
// global.ApplicationLoader
class ApplicationLoader extends PlayApplicationLoader {
  def load(context: Context) = {
   new ApplicationComponents(context).application
  }
}

// global.ApplicationComponents
class ApplicationComponents(context: Context) extends BuiltInComponentsFromContext(context)
  with ... {

  override lazy val httpFilters = Seq(
    ...
  )

  ...
}

// application.conf
play.application.loader=global.ApplicationLoader

// build.sbt
routesGenerator := InjectedRoutesGenerator
```

**Comment by fosskers** [comment]
Is there an ETA for that branch?

**Comment by EECOLOR** [comment]
I'll try to squeeze it in this week

**Comment by fosskers** [comment]
Thank you

**Comment by EECOLOR** [comment]
The branch has been merged and released. Please note that the organisation has changed from `nl.rhinofly` to `net.kaliber`. The README contains the required information.

**Comment by fosskers** [comment]
Thanks!
